drop table TIPO_CONTRATO;

drop table TIPO_TICKET;

drop table CARGO;

drop table COLABORADOR;

drop table COLABORADOR_ENDERECO;

drop table COLABORADOR_CONTATO;

drop table COLABORADOR_DADO_BANCARIO;

drop table DEPARTAMENTO;

drop table COLABORADOR_DEPARTAMENTO;

drop table ESCOLARIDADE;

drop table COLABORADOR_FORMACAO;

drop table COLABORADOR_DEPENDENTE;

drop table TIPO_EQUIPAMENTO;

drop table EQUIPAMENTO;

drop table COLABORADOR_EQUIPAMENTO;

drop table COLABORADOR_FERIAS;

drop table TIPO_HOLERITE;

drop table COLABORADOR_HOLERITE;



